### ISSUE TITLE
Leading zeroes for smaller trace-id. Should it be documented?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#140]
https://docs.google.com/document/d/1Zh871qWTew8Rzhz6jhFW0nxeC1ax1kAovQW8RFF5bCA/edit#

NewRelic uses shorter `trace-id`. Should we document "fill-in" characters and tell them to be in the beggining?

**Comment by yurishkuro** [comment]
the spec says "16 bytes". Is it not up to the vendor to decide how they want to pad if their ID is shorter? They still need to deal with another vendor sending fully random 16 bytes ID.

**Comment by codefromthecrypt** [comment]
if refering to traceparent, it is fixed width and zeros seem the more
reasonable choice of what to fill with (verses 1, 2, etc). This is the
same thing folks do when exporting to stackdriver 64-bit trace ids, as
well zipkin for last year or two (we treat left padded all zeros same
as no data, as all zeros is an invalid ID).

**Comment by codefromthecrypt** [comment]
agree with yuri that how they do it is more important to them vs
others. They could pad differently as the data is opaque, so saying
how to do it could just be a "for example" sort of thing, not in any
way a requirement.

**Comment by SergeyKanzhelev** [comment]
The question was mostly about what we can suggest them to make other's life easier. Some sampling algorithms may be sensitive to have less randomness in the beginning of the trace-id vs. in the end. Dapper takes last 4 bytes. So padding in the end may not be ideal. It's about making vendors more friendly to other vendors and for not means undermines the need to put enough randomness.

Alternative is to tell NewRelic to generate some random in the beginning instead of zeroes. Which I like more. And as @yurishkuro said they still need to deal with longer `trace-id`.

**Comment by codefromthecrypt** [comment]
in zipkin tracers, conventionally only sample on last 64 random bits. not
sure others but unclear what to put here vs elsewhere. for example it
starts sounding like describing a sampling algo

**Comment by SergeyKanzhelev** [comment]
@adriancole I think language of generating `trace-id` randomly will help interoperability. Basically it will force uniqueness and don't allow to simply do interlockedincrement on a single long value. Maybe test suite should test for non-repeating beginning and end of the `trace-id` after few calls.

Specifically for NewRelic implementation - leading zeroes cause many questions thus the issue. How to make it clear that padding is wrong or art least standardize padding.

**Comment by codefromthecrypt** [comment]
one thing to color this if about sampling is that the sampled flag is more
like the "primary" sampling status of the caller. in real life today even
on trace can be sampled several times at different rates even on the same
hop.

A primary consideration is helpful as otherwise too complex, and also
ensuring random sampling has a chance to work is also helpful. otoh you can
see where this goes :) that is why I am asking if we should be quite
prescriptive or not. or just say


 "bear in mind some systems do random sampling or re sampling at any place
in the trace.. so if you propagate a decision try to keep the right side of
the trace id random."

remember it isnt even for sampling 8 chars is quite short for other
indexing, so might be helpful to warn about the impact of tiny ids (like
log roll ups rolling up unrelated data due to very high collision risk)

in general I think best to suggest not padding and just full random.

**Comment by codefromthecrypt** [comment]
lines crossed maybe last comment addressed your question. I think small ids
are not good for what this is made for. the small ID can be in tracestate

**Comment by codefromthecrypt** [comment]
also food for thought  I think NR tracing system is very new. Maybe it has
less brownfield risk and can just do larger trace IDs? same question is
harder to ask for several year old deployments but even in zipkin which is
volunteer run we were able to grow ids to 128bit

**Comment by SergeyKanzhelev** [comment]
yes. @yurishkuro already asked this: https://github.com/w3c/distributed-tracing/issues/79. I think NewRelic implementation make us think again how to make it more clear that random and full ID is important. I'll put language similar to what you suggesting.

NR will update to longer ids... but maybe not soon. And this implementation is just indication that additional language is needed.
