### ISSUE TITLE
Do we need a response header?

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#148]
This issue relates to #50. 

##  Rationale
We can see that this can have value, but don't think right now is the right time to standardize. We decided to rather wait for problems to come up during implementations and then decide how to move forward. 

**For now this will not be part of the Trace-Context specification**

## Open Issues
- Are they required or optional?
- How are they propagated upstream? Is this done via multiple hops?

## Use Cases
- Restart a trace and return information to caller.
- Notify upstream to sample trace sendin a sampling flag (+ sampling score) for delegated sampling
- Send Tenant ID/identity of the service so caller knows where to query telemetry from
- Report back data to the caller (like server timing)

## Potential Content of a Header
- TraceParent, TraceContext
- Sampling Options
- A human readable name for the service (if you only have an IP address or DNS names)

## Problems*
- Might not work in all scenarios (e.g queues)
- Not sure what processing etc. would look like.

**Comment by SergeyKanzhelev** [comment]
Added rationale. Issue needs to be re-open for future release when we will decide to talk about it again

**Comment by codefromthecrypt** [comment]
completely agree on this one. a couple things:

I think amazon (abhishek etc) are using backtrace. when closing something
it is nice to mention them on github so they are alerted. this might or
might not mean an adoption risk.. if so that could also be noted. at very
least alert folks directly as following this repo can be a bit much.

nit: I don't think it is a maybe on queues ;) it won't work in any one-way
thing by nature.
