### ISSUE TITLE
How does the trace-context distinguish "child of" from "follows from"?

### ISSUE THREAD

**Issue by smullins3000** [w3c/trace-context#202]
As I understand it there are two main relationships between spans. You use child-of when the child span is contained within the parent and follows-from when the parent "spawns" the child but isn't dependent on the child. (I think of them as synchronous vs. asynchronous).

How does the "traceparent" header distinguish these cases? Is that left to the implementation specific portion in tracestate? Alternatively, the assumption might be that all of the work of the web service is assumed to be completed when the child web service responds and that therefore all web service calls are inherently "child of". 

FYI, I am relatively new to opentracing so I may have severe misapprehensions. Apologies in advance.

**Comment by AloisReitbauer** [comment]
Trace-Context does not distinguish between these two cases. This will be part of the tracing data that gets exported by a tracer. For linking the difference is not relevant

**Comment by yurishkuro** [comment]
@smullins3000 the difference between child-of and follows-from typically is implied by the protocol used between client and server. E.g. an RPC call implies child-of since the client is expecting a response, where as messaging over Kafka implies follows-from since the publisher has no knowledge (usually) of when the consumer will get the message, and therefore is not expecting a response.

in OpenTracing the child span decides if it wants to use child-of or follows-from reference to the parent. There's usually no need to propagate anything extra aside from the parent ID in the trace context.

**Comment by smullins3000** [comment]
It makes sense that it is the spawned process that determines child-of or follows-from. 

Thank you.
