### ISSUE TITLE
Mechanism to audit randomness of trace-id

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#210]
Similar to https://github.com/w3c/trace-context/issues/79. During the privacy review there was a suggestion to think about audit for IDs randomness. Possible suggestion was to potentially document IDs generation algos. For instance, if randomness is coming from some time-based calculation one can audit it by ensuring it's in boundaries of a give time. So nobody can inject IP address or other information into the trace-id. Perhaps it can be suggested as a measure for some enclosed systems.

**Comment by plehegar** [comment]
Relevant notes from the call:
[[
@samuelweiler : 1) auditing, can we audit whether the information included in trace headers is acceptable (doesn’t include sensitive, PII, etc.)? rather than any random number, limit to hash of a recent timestamp, so that it’s less easily abused

@SergeyKanzhelev : an interesting idea to be able to audit, so that people can’t put information within the mostly random identifier
]]
https://www.w3.org/2018/11/29-privacy-minutes.html#item00

**Comment by SergeyKanzhelev** [comment]
Resolved via #273
