### ISSUE TITLE
Should implementation propagate flag it doesn't know about

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#296]
Spec is ambiguous now

**Comment by discostu105** [comment]
This issue is about the following scenario: What if an incoming Traceparent header has `trace-flags` set that are currently not specified. Should the flags be propagated unmodified? Should the flags be dropped?

In my opinion, the correct behavior would be to drop flags that are unknown/unspecified to an implementation. We cannot predict the semantic of future flags, so propagating them unchanged would possibly be wrong.

**Comment by danielkhan** [comment]
Covered in the current spec
