### ISSUE TITLE
What is the milestone of this spec?

### ISSUE THREAD

**Issue by wu-sheng** [w3c/trace-context#31]
I am aware there are definitely plenty details to discuss for this spec. But, I suggest we can do some works in implementation level. For do that, we should set a milestone, like 0.1 or 1.0, as you like. So the tracer/APM-agents can try to implement the spec, and find out what is next for everyone.

@adriancole @bogdandrutu @SergeyKanzhelev

**Comment by mtwo** [comment]
I'm a fan of having a milestone list available this week and then locking down v0.1 at the November meeting

**Comment by bogdandrutu** [comment]
We have a milestone defined here:
https://github.com/TraceContext/tracecontext-spec/milestones

Please edit if you want to have some explicit things there.

**Comment by wu-sheng** [comment]
Although @adriancole has invited me, but I am sure whether can be at Sydney or not. 

@mtwo @bogdandrutu @SergeyKanzhelev IMHO, I think the spec is ready for 0.1 release. Version issue #32 is still debatable, and properties of a Correlation Context value are not high priority things. 

FYI, the certain length of traceid and spanid , #19  is the last block for skywalking.

**Comment by mtwo** [comment]
@bogdandrutu @wu-sheng @adriancole @SergeyKanzhelev @bhs @cce @jkowall @yurishkuro @vancem @abhiksingh @rakyll @mattklein123 @codingfabian @jkowall and anyone else following along, here's my proposal for a first release:

I've created a [milestone for v0.1.0](https://github.com/TraceContext/tracecontext-spec/milestone/1), which represents the first release of TraceContext. v0.1.0 will be very basic, and will include:

- An HTTP header name
- Trace ID
- Span ID
- An options bitfield
- An encoding format for the header and its components

I also propose that we follow up with support for baggage and correlation context in subsequent versions. I don't think that we should include them in the first release as they're (somewhat) less important than aligning on an ID space and encoding format, and because we can add them without making breaking changes.

It looks like the biggest / most opinionated open issue is #19, so I propose that we spend the next week attempting to solve it by consensus, and that we vote on it and any other open issues on November 2nd or 3rd. @adriancole had already organized one of his regular tracing workshops in Sydney at this time, which seems like a good forum for the discussion and vote as a number of the participants will be there and because the timezone is quite friendly to most of the participants.

Does this seem reasonable? I think it's a good balance of expedience and fairness, but I'm happy to take feedback!

**Comment by mattklein123** [comment]
+1 from me. Let's do this!

**Comment by SergeyKanzhelev** [comment]
@mtwo if `Correlation-Context` not controversial, do you want to take it as well? Two of them make more complete story to start adopting.

**Comment by mtwo** [comment]
@SergeyKanzhelev fair enough, let's vote on adopting each one at the same meeting? Sound good?

**Comment by yurishkuro** [comment]
Please reserve the voting for github, not everyone can make the meeting.

**Comment by wu-sheng** [comment]
@mtwo As I have feedback to @adriancole , because I can't have enough time to get Aus VISA, I have to absent the meeting. But skywalking is interesting in this.

**Comment by mtwo** [comment]
Sounds good Yuri and Sheng, let’s use the meeting / video conference for discussion and then vote on GitHub.

I’m thinking that one vote per vendor / OSS project probably makes the most sense but am open to feedback. Sound good? :)

_____________________________

**Comment by CodingFabian** [comment]
I think its a good first step. But until we talk about how to identify IDs from other vendors and link to their parts of the trace, we will potentially cause new problems where trace ids are mistaken.
This then also brings up how to preserve foreign ids (many tracers will be unable to apply their internal optimizations for trace id storage (like using primitive types))

**Comment by mtwo** [comment]
@bogdandrutu @adriancole @SergeyKanzhelev @AloisReitbauer @abhiksingh @tylerbenson

At the Sydney meeting, we discussed the following:

1. A trace-context header, which is composed of fixed length ordered fields for performance. These fields include a version, trace ID, span ID, and a bitfield indicating things like the sampling decision.
2. A correlation-context header, which allows additional fields to clarify the trace-context. This header is similar to baggage in the sense that it is a set of key value pairs, but it is only written to by vendor / library code - end users should not be able to directly set its values and make it a core part of their application logic. This field has a maximum size, beyond which it will be dropped by instrumentation systems.

Correlation context will likely be used to hold things like epoch seconds (Amazon) or hierarchical IDs (Microsoft). Vendors should prefix their key names to avoid collisions.

What we need now is:

1. Encodings and some basic rules like max sizes for the proposed trace-context and correlation-context formats. I'm not the right person to provide these, so I'm arbitrarily nominating @adriancole and @bogdandrutu to either produce a proposal or to deputize someone else. If someone else is willing to do it, please reply in this thread.
2. A vote on GitHub. I can oversee this once the first step is complete.

I'm currently on vacation but I'll check in on this thread to respond to questions or kick things if we aren't making progress.

**Comment by SergeyKanzhelev** [comment]
Milestones are now described in [charter](https://w3c.github.io/distributed-tracing/charter.html) for working group
