### ISSUE TITLE
Version in header

### ISSUE THREAD

**Issue by mnot** [w3c/trace-context#32]
I don't think you need a `version` in the header, because:

1. If you eventually need to revise the format, you can introduce a new header (either as a replacement, or as additional information)
2. It implies some means of version negotiation (which you don't have AFAICT)
3. Generally, you only get one go at this anyway :)

**Comment by abhiksingh** [comment]
I do think having a version is important whether it's part of the trace ID or a separate header is open for discussion. Having a version provides future flexibility to iterate/improve the spec with backwards incompatible changes if necessary. In an ideal world all future changes would be backwards compatible so that end users aren't impacted but having a version seems like a fair trade-off to enable the group to make backwards incompatible changes to the spec in the future if absolutely necessary.

To @mnot point around version negotiation, I do think we should add something to the spec that at the very least requires implementations to check the version while validating the trace context.

**Comment by mnot** [comment]
> whether it's part of the trace ID or a separate header is open for discussion.

That's the discussion I'm raising -- pointing out that you get other versions for free by changing header field names (as is common practice; how many other header fields have an embedded versioning scheme?)

**Comment by SergeyKanzhelev** [comment]
@mnot the hope is to preserve header name. So proxies will propagate it and browser can whitelist it for AJAX calls in `Access-Control-Expose-Headers`.

Also +1 for @abhiksingh that basic sanity check is helpful to make libraries more reliable.

I'm closing this issue for now. instead opening https://github.com/w3c/distributed-tracing/issues/54. Let's re-open discussion about version number when time will come for the revision.
