### ISSUE TITLE
Clarify handling of duplicate keys in tracestate

### ISSUE THREAD

**Issue by tsloughter** [w3c/trace-context#369]
Discussing on gitter last week it was not clear from the spec how to handle duplicate keys in a received tracestate.

The tests require the tracestate is dropped in such a case: https://github.com/w3c/trace-context/blob/98f210efd89c63593dce90e2bae0a1bdcb986f51/test/test.py#L536

The example in the spec about going through a system twice is also a bit confusing, https://w3c.github.io/trace-context/#combined-header-value

I think it would make more sense, even though it is an example of what shouldn't be used, to say it shouldn't be `congo=congosSecondPosition,rojo=rojosFirstPosition,congo=congosFirstPosition` simply because the newer entries should come first.

**Comment by danielkhan** [comment]
If a system follows the spec, duplicate keys can not occur. As such a header with duplicate keys is considered to be invalid.

I think it's questionable if the suggested example would be more correct as it would mean flipping `congosSecondPosition` and `congosFirstPosition` but I will bring it up at the next meeting.

**Comment by danielkhan** [comment]
The tests are too rigid and test non-normative rules and we should modify them.

**Comment by danielkhan** [comment]
@reyang do you have time to look into this?

**Comment by reyang** [comment]
@danielkhan it is unclear to me what's the expectation for the test cases:
1. Do we expect the [Test Service](https://github.com/w3c/trace-context/tree/master/test#implement-test-service) to take `tracestate` that has duplicated keys, instead of drop it on the floor? - I guess the answer is YES.
2. Do we expect the [Test Service](https://github.com/w3c/trace-context/tree/master/test#implement-test-service) to send the `tracestate` without de-dupe, or it should de-dupe the keys before sending it out? - I guess the answer is YES.

**Comment by danielkhan** [comment]
Sorry for the long wait. Let's go for 1.)
For 2. just forward without de-dupe.

**Comment by dyladan** [comment]
@reyang sorry to ping you on this after so long but did you ever get around to this?

**Comment by reyang** [comment]
@dyladan nope I didn't.
