### ISSUE TITLE
Clarify use of trace-id in response header

### ISSUE THREAD

**Issue by dyladan** [w3c/trace-context#407]
After feedback from @adriancole it became clear that the use-case for trace-id is not well defined in the spec. Update the wording to make it clear that the caller is not meant to adopt the trace id.

**Comment by yurishkuro** [comment]
The use case for returning trace ID is when cloud provider returns an internal trace reference. What is the proposed alternative for that use cae?

**Comment by dyladan** [comment]
There is no proposed alternative. The issue is that the use case you stated wasn't clear to everyone. This issue is just to remind me to take a look through the spec and make sure it's clear that this is the intended use case.

**Comment by yurishkuro** [comment]
My understanding is that the use case is:
  * Client sends a request to a managed service in the cloud. Client may or may not include traceparent.
  * Cloud provider internally starts another trace, and returns its ID in the response header.
  * Client records the response trace ID in its own span/trace, or logs it, so that it can be given to cloud customer support for troubleshooting.

When I say "trace ID", it may also include the span ID, if the cloud provider wants to have more precise reference (perhaps in some messaging / serverless scenarios the reference is not always to the root), but that's a speculation.
