### ISSUE TITLE
Document rationale for 255 leading spaces in tracestate values or remove it

### ISSUE THREAD

**Issue by codefromthecrypt** [w3c/trace-context#409]
@reyang changed the spec to allow 255 leading space characters and @SergeyKanzhelev merged it the next day. There was zero rationale for this, yet it is very unintuitive

w3c/trace-context#135

As the intuitive behavior was reversed, we need an explanation. This makes for very strange parsers especially odd when so much thrash happened in the name of making parsing easier in the past. This has caused a couple people to scratch their heads and it is unacceptable for a change like this to have been merged in the first place.

I raised a comment there. but it was ignored, so making this an issue instead. Here's the comment:

trying to understand why this is allowing 255 spaces before a non-space.

#188 has a lot of talk about impact of presumably having a trailing empty member. I saw no code references, just talk about test cases invisible to open source, yet used to justify that change. Regardless, this literally permits 255 empty spaces than a non-space. If what's said in 188 is true, and that libraries arbitrarily add white (please cite exact libraries and versions).. what does this help?

I think it just makes sure space is only allowed for left-padding a non-space. If correct, the description should be updated. If incorrect, I guess I am misreading the abnf and would appreciate knowing how.

**Comment by codefromthecrypt** [comment]
concretely I think #135 should simply be reverted

if it isn't reverted, in the http rationale mention the importance of leading space preservation, and then underscore in the text under the rationale something easy for people to miss... which is that the ABNF is saying you have to preserve any leading spaces as otherwise you will break the sender of it.

**Comment by dyladan** [comment]
I wasn't around at the time this change was made, but it doesn't really make sense to me and the PR gives basically no context. Reverting #135 is not a backwards compatible change, which is unfortunate. Is it causing some issue in your parser, or are you simply making the case that changes in general should not be made this way?

**Comment by dyladan** [comment]
Maybe @reyang can give some context?

**Comment by reyang** [comment]
Here goes the history:
* The original ABNF was totally broken and had ambiguous grammar. `value    = chr 0*256(chr)` which means the trailing spaces could either be treated as part of the value, or the OWS (optional white space).
* I fixed the ambiguous grammar in PR #131.
* Then I noticed that my PR #131 has introduced more restriction - the previous syntax would allow a value to have heading spaces, but the new syntax wouldn't allow that.
* I then submitted PR #135 to make sure the ABNF is as flexible as it was before #131, yet with no ambiguous grammar.

**Comment by danielkhan** [comment]
@SergeyKanzhelev could you take a look as well?

**Comment by dyladan** [comment]
@adriancole we talked about this in the meeting today.

As far as we can tell, the current wording matches the ABNF. Here is the current version for reference:

>The value is an opaque string containing up to 256 printable ASCII [RFC0020] characters (i.e., the range 0x20 to 0x7E) except comma (,) and (=). Note that this also excludes tabs, newlines, carriage returns, etc.

```
value    = 0*255(chr) nblk-chr
nblk-chr = %x21-2B / %x2D-3C / %x3E-7E
chr      = %x20 / nblk-chr
```

According to this, any leading space on the value is _part of the value_, and not optional whitespace. Therefore, it cannot be stripped as it may be meaningful to some vendor because this is an opaque string and we can't assume anything about it.

`key1=   value` decomposes to 
```
{ key: "key", value: "   value" }
```

Reverting #135 to make that leading whitespace optional whitespace, and therefor trimable, would be a backwards incompatible normative change. We could consider this for version 2, but because it is backwards incompatible we would need concrete reasoning.

We could not, at the meeting, determine if your issue is with this behavior itself, or with the process by which it was introduced. @reyang provided some history, but at the time it seems there was less process involved which helped get some changes in quickly, but also makes it difficult to divine the reasoning behind some changes. If your issue was with the behavior, we can talk about reverting it for version 2. If your issue is with the process only, I think it is unfortunate but we should not make a backwards incompatible change without a behavior-based reason.

Is there any other way you can think of to resolve this in a backwards compatible or non-normative manner?

**Comment by anuraaga** [comment]
@dyladan It's admittedly pedantic, but to this point

> The value is an opaque string containing up to 256 printable ASCII [RFC0020] characters (i.e., the range 0x20 to 0x7E) except comma (,) and (=). Note that this also excludes tabs, newlines, carriage returns, etc.

does it actually match? 256 printable ASCII (0x20-0x7E) seems to allow a value with 256 spaces and no non-space. But the grammar does require one non-space, and it forbids trailing spaces. The grammar is probably like this to prevent a conflict with `OWS` but IMO does not match the text anymore. This sort of text would I think

`The value is an opaque string containing up to 255 printable ASCII (i.e., the range 0x20 to 0x7E)) followed by one non-space printable ASCII (i.e., the range 0x21 to 0x7E)`

That being said, this seems like an implementation detail to prevent conflict between printable ASCII and OWS and doesn't have any real semantic merit - it's very unintuitive to forbid trailing space but allow leading space. For a truly opaque string, we'd expect both to be preserved, or otherwise trimming both sides seems intuitive to allow. Whether this unintuitiveness is enough to warrant a backwards incompatible I don't know, but making the text in the spec more precise and documenting why it's like that either in the spec, or errata or as some separate rationale doc linked from there, would be useful to reduce confusion.

**Comment by dyladan** [comment]
@anuraaga yes that is exactly why it is like that, to prevent OWS from conflicting.

Also, if we're playing the pedant game, all 256 characters are still printable ASCII even if one of them is required to be a non-space 😉 .

If it is really a problem, I would propose this for the wording:

>The value is an opaque string containing up to 256 printable ASCII [RFC0020] characters (i.e., the range 0x20 to 0x7E) except comma (,) and (=) which must end with a character which is not a space (0x20). Note that this also excludes tabs, newlines, carriage returns, etc.

This could be considered a non-normative change if the ABNF (and behavior) is unchanged, and the wording is changed to match it more clearly.
