### ISSUE TITLE
Should standard define a way to tell which tracing vendor is being used?

### ISSUE THREAD

**Issue by elgris** [w3c/trace-context#53]
For instance, one of HTTP headers `User-Agent` is being used to provide (optionally) information about the caller. 

In a world of distributed tracing it may be useful to provide a callee a hint about the vendor-specific format of the trace. So the callee can properly process data in `Trace-Context-Ext` header. In such  case, should the standard define another optional header that contains the name of trace format or a vendor? Or should it suggest using standard `User-Agent` header for that?

**Comment by SergeyKanzhelev** [comment]
@elgris you can use `Trace-Context` to store this information. And the best way would be something similar to browser capability detection. Look for the key (or keys) you need and if they all defined - treat the input as well-known input from well-known vendor.

If you must know the immediate caller's vendor - the only way would be to pass an additional header. Since that additional header is not a part of standard - it will not be blindly propagated. So you have at least some guarantee that if that extra header present - there were no "unaccounted" trace context modification in the middle.

One example we discussed is hierarchical ID (aka vector). The idea of hierarchical ID is to be incremented on every layer of processing. First component send `1`, than `2`, than `3`. Second component when received `2` sends `2.1`, `2.2`, ... third component `2.1.1`, `2.1.2`, `2.1.3`, etc. So all components need tp increment vector. However if there is a component in the middle that do not know about vector, but can change the `span-id` you may get some questionable results. Spans will share the same vector, but will have different `span-id`. So you have two options - make the backend resilient for this situation. Or explicitly pass information on whether vector was incremented. We are discussing now inside MS what would be the right approach here. 

Maybe one thing how spec can help is by defining TTL=1 on certain trace-context properties: https://github.com/w3c/distributed-tracing/issues/23

What scenario you have in mind? Is this scenario resilient to components controlled by the different vendor in the middle?

**Comment by elgris** [comment]
@SergeyKanzhelev I'm thinking about scenario that is likely to happen in a big heterogenous organisation (I currently work for). Imagine following case: there is a serviceA  that participates in distributed tracing and reports tracing data to some proprietary vendor, let's say, [Instana](https://www.instana.com/). In order to retrieve specific data it needs to know how to process properly headers `Trace-Context` and `Trace-ContexExt`. 

Then it receives a request coming from the "outer world". And the sender (service B) knows nothing about that proprietary vendor I mentioned above. Instead, it reports data to, let's say, Jaeger. And it encodes data into headers `Trace-Context` and `Trace-ContexExt` according to Jaeger specifications.

The problem is that content of `Trace-Context` is not consistent from request to request. In some cases values from there should be processed in some special way. That's why I asked if the standard should define something providing information about the vendor.

**Comment by codefromthecrypt** [comment]
I think we discussed in the past that you have to restart a trace that you
decide not to trust or can't process the trace-context-ext of. This seems
to be a discussion of how to identify a trace-context-ext (remember if this
doesn't exist, then it is portable anyway). Do I get it right?

**Comment by SergeyKanzhelev** [comment]
+1 to @adriancole 

Another point here is that `Trace-Context` format and semantics is fixed. So ideally nobody will secretly encode some extra information into it. And should not expect this information will be preserved. The great idea of common specification is that you can install service mash between two components you mentioned. It can modify `span-id` or add properties to `Trace-Context-Ext` to be read by another service mash between service `B` and service `C` it calls. And this information will not harm whatever tracing mechanism you have on service `B`, but will enrich telemetry reported by that service mash.

**Comment by SergeyKanzhelev** [comment]
@elgris please re-open if you feel strongly about this and you have scenario where standard wouldn't be complete and may lead to problems
