### ISSUE TITLE
Define behavior when library do not understand the version number

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#54]
The behavior may differ between not being able to parse header and unknown version number. Spec should make some considerations for the versions revision in future.

**Comment by SergeyKanzhelev** [comment]
I was thinking about this one. I feel we can make a good use of `tracestate` here. So if one sees unknown version prefix - behavior may be the following:

- Pass-thru the `traceparent`
- Start a new trace. Let's say it's `00`. Place it into `tracestate` like:

Incoming:

```
traceparent: 02-abcdefg
tracestate: vendor1=opaqueValue1
```

Outgoing (from the system that only knows about `00`):

```
traceparent: 02-abcdefg                                        //unchanged
tracestate: v00=00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01, vendor2=opaqueValue2, vendor1=opaqueValue1
```

This will require:
1. Reserver `vXX` keys in `tracestate`
2. Recommendation: define the size limit as a sum of `tracestate` and `traceparent`. So size-critical systems will be able to deal with higher version of a header if it will be longer. It will just eat up some `tracestate` space
3. Parsing will be a bit more involved for the cases with the unknown version of `traceparent`. Now you'd need to look up `v00` header in case it was already started before.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro since you seems to be around - do you have an opinion here? Does this approach looks reasonable for you?

**Comment by yurishkuro** [comment]
Sorry, I don't have an opinion about this. I'd like to see first the whole thing working even with a single version and understand all the edge cases before prescribing behavior for mismatched versions.

On the first glance, adding `v00=` seems unnecessary, since the next hop will received v0 `traceparent` and its own state may or may not be found in the tracestate.

I think downgrading the version is reasonable and should be allowed, while upgrading the version should not be allowed. Aside from that I don't know if we need any other prescriptions.

**Comment by SergeyKanzhelev** [comment]
>I think downgrading the version is reasonable and should be allowed, while upgrading the version should not be allowed.

Can you elaborate on this? My thinking was quite opposite. If downgrading will be the default behavior than it will be very hard to move to the next version. Any component that is stubborn to upgrade will break features of the next version.

**Comment by yurishkuro** [comment]
When a node receives N+1 version but only understands N, it has no choice but to start a new trace. So if you have A->B->C where A and C only know N, but B upgrades to N+1, then it will force a broken trace in C even if it didn't have to. If both A and B understand N+1, then the trace will still be broken at C, but nothing could be done.

So upgrading potentially forces a broken trace when it could've stayed unbroken.

**Comment by SergeyKanzhelev** [comment]
> So if you have A->B->C where A and C only know N, but B upgrades to N+1, then it will force a broken trace in C even if it didn't have to.

So while upgrading from lower version - this lower version should be moved to `tracestate`. It will indicate that upgrade has happened.

> If both A and B understand N+1, then the trace will still be broken at C, but nothing could be done.

In this case if C will simply pass thru `traceparent` - it will became invisible for the A->B correlation. But B will know something happened because there will be new `tracestate` update with `v00` key.

It is a great point that if component wants to upgrade - it needs to preserve original one in `tracestate`!

**Comment by nicmunroe** [comment]
I'm a little confused with the use case here - are we talking about a case with A->B call, and both A and B are using the same tracer/vendor, but A is sending a version format that B doesn't understand? Or is it different tracers/vendors between A and B?

Maybe the answer is the same in either case - B has to start a new trace for its trace graph unless it finds something in tracestate that it understands, yes/no?

**Comment by SergeyKanzhelev** [comment]
This issue is about how we will migrate to the new format when time will come. The idea here is independently from vendor - it is important to keep newer version flowing in `traceparent` to promote progress. And you need to look for version you understand in `tracestate` collection under well-known name.

All this assume that `tracestate` does not require versioning

**Comment by nicmunroe** [comment]
`traceparent` is just telling you what your immediate predecessor did, not what the entire call-chain is doing, yes/no? All the "real" state for a given tracer/vendor is going to be in `tracestate`, and since `tracestate` values are opaque and tracers/vendors can version their state completely independently of the the incoming call's `traceparent` version, the `traceparent` version doesn't make or break what the receiving service is doing. I think? 

I feel like I'm missing something here. Could be entirely on me.

**Comment by codefromthecrypt** [comment]
I am also a bit confused but can hazard a guess.

are we simply saying trace state owners "may" consider the version number
in the transparent header? even if this were the case we are supposed to
not depend on anything in traceparent.. even if it were a choice to, that
would be trace state format specific right?

can we come up with motivation where this matters and how any choice here
would affect something albeit docs or impl?

**Comment by codefromthecrypt** [comment]
I think maybe 2 issues.. how we handle version updates in traceparent and
if state definitions are traceparent version specific.

personally I think the tracestate cannot be traceparent version specific.
maybe we discuss this next week?

**Comment by SergeyKanzhelev** [comment]
yes. Let's discuss it on workshop. 

This proposal is just clearing up the way for spec evolution. Since we including the version prefix in `traceparent` we need to explain how to deal with the unknown version. Throwing everything away as "incorrect format" and restarting trace is not ideal for future trace evolution. Thus this proposal.

**Comment by nicmunroe** [comment]
My main concern on this is that we may be trying to define behavior for something we can't really predict yet. It may be that any future change we want to make to `traceparent`'s version has no effect on `tracestate` or is otherwise backwards compatible. Or there may never be a version update, period. By defining this logic up front we require implementers to have to code it up front too, and we may be creating a bunch of rules that are way more complex than what we actually need in the future.

On the other hand I can see how if there's nothing defined now regarding version changes, then there's no automatic support from tooling if there are ever any version changes, leading to the non-ideal "throw it away and start over" scenario.

Not sure how to balance those tradeoffs.

I think I agree with Adrian that we should encourage implementers to not be `traceparent`-version-specific when defining their `tracestate` opaque value format.

**Comment by SergeyKanzhelev** [comment]
I think main principles here:
1. Change of header name is the most unwanted behavior. Thus the version prefix in `traceparent` header value.
2. Restart of a trace is also unwanted behavior.
3. Version upgrade should be respected by older components. This will ensure progress.
4. Rules should be straightforward.
5. `tracestate` is least likely to be changed as the values there are opaque. 

Do you agree with these principles?

If so - proposal basically is to put older components in a position of a different vendor which propagates it's headers via `tracestate` alongside it's other values. I understand the potential complexity of implementation - extra string will need to be kept in memory and there will be complexity of parsing. But semantically this rule is easy to explain.

**Comment by yurishkuro** [comment]
> Version upgrade should be respected by older components. This will ensure progress.

As I mentioned [in the example above](https://github.com/w3c/distributed-tracing/issues/54#issuecomment-382145416), I don't agree with this - it will ensure broken/restarted traces. Also, by definition older component cannot respect version upgrade if it doesn't understand the format of that version. It needs to mutate traceparent, but it only knows how to encode that mutation in N-1.

**Comment by SergeyKanzhelev** [comment]
are we on the same page that unless we want to minimize the need to predict the future versions. Instead we should preserve the "N+1" or "N+2" or any other higher version header one way or another. One way is to preserver in `traceparent`. Another is to preserve in `tracestate`.

If you thinking like I'm thinking here - implementing your proposal will be easier than mine. Basically we are saying: 

1. if version prefix is higher than you understand (`01`)
 a. Put entire `traceparent` into `tracestate` under the name `v01`
 b. Search for `v00` in `tracestate`. If exists - mutate it and put into `traceparent`. If doesn't create new `traceparent`. Keep `tracestate`
2. If version prefix is higher - do opposite.

Second item needed to allow trace vendors that upgrades from `00` to `01` keep `00` vendors connected. Transition will be smoother.

This way vendors will not need to keep an extra string that needs to be propagated instead of `traceparent` you operate with.

Is it your thinking?

**Comment by SergeyKanzhelev** [comment]
Work in progress comment during the implementors workshop... 

We want to preserve as much back compat as possible between versions. So perhaps we should force all future versions to start with the existing header and then have new parts later. Those rules do not account for this:

Rules:

0. Pass thru should not analyze version. Pass thru service needs to expect that headers may have bigger limits in future.
1. Unknown prefix (non hex-hex-dash): restart trace. (MAYBE put a note that app MUST NOT be crashed because of illegal format).
2. Higher version:
  a. Try parse `trace-id`: from dash 32 characters. Make sure followed by dash. 
  b. Try parse `span-id`: Only try if `trace-id` was parsed. From the second dash 16 characters. Make sure followed by dash. 
  c. Try parse flags: Only try if `span-id` was parsed. From dash 2 characters. Following with either end of string or dash.

You need to downgrade to the version you know about.

Traceoptions - can we add a bit without updagrading the version?

NOT:
You MAY preserve original unknown value in tracestate? may lead to abuse. Not adding this wording.
Do not (you still MAY) validate for hex while parsing trace-id and span-id

**Comment by codefromthecrypt** [comment]
I'm not sure which implementors were present or if implementors are the
same as the normal workshop or what, but in addition to what Nic mentioned,
we are now changing traceparent into a semi-validated field.

This implies carry'ing "junk" which might be abused not just from a normal
sense, but for example, people intentionally misusing it, and now libraries
have to carry that penalty (not to mention the bandwidth).

Technically, I would expect an implementers POV to include code impact
which is why I ask about who was present, if they are in use or not etc.
For example, now, you have to split a string further and also carry it
around. This is more overhead than before, more SPI surface area as well,
as that "trailer" needs to be re-attached depending on whatever rules are
defined.

Since we already have a chaos area subject to abuse: tracestate, I wonder
why we are also adding it here, and what motivated it? Is someone trying to
get something in? there must be some concrete use cases or other new
information or at worst we are re-hashing also without implementor pov.

**Comment by SergeyKanzhelev** [comment]
who was there: https://docs.google.com/document/d/1ekFjRD9rUZsmI98-fcBu8abx7BpQgDbrJjDZ6FvnB-s/edit#

There also was a discussion on gitter

Versioning options are:
1. Pass thru unknown headers
2. Re-start trace when you see unknown header
3. Try to parse trace following some rules when you see unknown header

One variation is whether original or new header you cannot recognize is preserved in `tracestate`.

Option 1 is least favorable as it makes one bad header break entire distributed trace.
Option 2 is better. It's easy, doesn't restrict future version in any way and re-started trace should be understood by new systems. So only one "connection" is lost. And the lost connection issue can be solved by storing original header in `tracestate`. Drawbacks are also obvious. First, single old component always breaks traces. Second, it's harder to transition without customer dissat of broken traces. 

Storing original value also has negative effects. Valid `traceparent` is 55 characters (out of 512 allowed for `tracestate`). And "bad" headers could be much longer pushing valuable `tracestate` pairs out. Also this requirement increases the chance of abuse. When bad actor will start sending header with the version `99` that is only understood by that actor. And the fact that every system passes thru original value allows this actor to build complete solution based on this header.

So we discussed option 3 with the fallback to option 2. Initial proposal was to try to parse individual parts like `trace-id` than `span-id`. Assuming `span-id` size or format may change without changing `trace-id`. However majority sees potential for abuse here. So we suggest to force future versions be additive to the current format. And if parsing fails at any stage - simply restart the trace.
