### ISSUE TITLE
Charter questions from W3C review

### ISSUE THREAD

**Issue by wseltzer** [w3c/trace-context#98]
@dontcallmedom asked a few questions while reviewing the draft charter, and gave me permission to post them here. Thanks!

* the mission statement, while concise, is probably going to be hard to
understand for many - "tracing tool" is pretty vague if you're not in
that business. The first sentence of the scope section might benefit
from being brought up here

* "Testing plans for each specification, starting from the earliest
drafts" is not a complete sentence

* probably related to the above on implementations, do we know what a
test suite would look like for this work?

* is there any reason to think that facilitating the interop of traces
would impact negatively privacy? i.e. is there "privacy through
obscurity" that this would weaken?

* the link on "Trace Interchange format" should be removed (since it
goes nowhere)

* from what I can see, there has been no incubation on the interchange
format yet; should that be a concern per the Rec-track readiness criteria?

* given we are already in April 2018, the timeline probably needs to be
shifted for the first few items

* I have a hard time parsing "The trace context standard is also
applicable to be implemented for work done within the web performance
working group." - maybe simplify and illustrate?

**Comment by dontcallmedom** [comment]
another point that I raised:
*  what counts as an "implementation" in the above is not entirely clear to me either; is it consumer of traces? providers? intermediaries? the draft specs refers generically to "platforms and libraries", but that remains pretty vague

**Comment by AloisReitbauer** [comment]
I will work on a revised version over the next week. Here are some initial comment on the points stated:

the mission statement, while concise, is probably going to be hard to
understand for many - "tracing tool" is pretty vague if you're not in
that business. The first sentence of the scope section might benefit
from being brought up here

**Alois: will do**

"Testing plans for each specification, starting from the earliest
drafts" is not a complete sentence

**Alois: will rework**

probably related to the above on implementations, do we know what a
test suite would look like for this work?

**Alois: We are currently working on a test suite. The main idea is to define an incoming HTTP requests as input to the test code. The output is the response header and the request header for a next-step validation tier. For all the outputs there will be a defined set of expected values**

is there any reason to think that facilitating the interop of traces
would impact negatively privacy? i.e. is there "privacy through
obscurity" that this would weaken?

**Alois: No, I don't think so. The actual trace data is only available in a data store that is protected by vendor-specific security.  In other words, while you might have an ID for a trace, you have no access to the data behind this ID. There is also no way to derive other information from the trace header like which user sent the request, etc.**

the link on "Trace Interchange format" should be removed (since it
goes nowhere)

**Alois: Will do**

from what I can see, there has been no incubation on the interchange
format yet; should that be a concern per the Rec-track readiness criteria?

**Alois: We decided to have the trace headers ready first. They are also a prerequisite for the interchange format to have any value. The headers by themselves also already solve an isolated problem even if the data formats are not standardized**

given we are already in April 2018, the timeline probably needs to be
shifted for the first few items

**Alois: Will do**

I have a hard time parsing "The trace context standard is also
applicable to be implemented for work done within the web performance
working group." - maybe simplify and illustrate?

**Alois: I will make the relation to Server Timing clear**

what counts as an "implementation" in the above is not entirely clear to me either; is it consumer of traces? providers? intermediaries? the draft specs refers generically to "platforms and libraries", but that remains pretty vague

**Alois: An implementation or tracer is an application component - usually an agent or a library - that forwards trace state or trace data**

**Comment by wseltzer** [comment]
@dontcallmedom do the changes in https://github.com/w3c/distributed-tracing/commit/ff1ce6dbc957930bac29b75c900f18f5e3fa1abe address your comments?

**Comment by dontcallmedom** [comment]
they do, thanks!

**Comment by wseltzer** [comment]
Great, we're ready to send the charter for W3C Advisory Committee review (and to close this issue).

**Comment by wseltzer** [comment]
Draft charter posted on W3C site: https://www.w3.org/2018/04/distributed-tracing-wg-charter.html
(with a few typo-edits and updates to Process links).
